version: "3"
services:
  app:
    image: jatb:latest
    container_name: jatb
    restart: always
    build: ./
    ports:
      - "${PORT}:8081"
    links:
      - mongo
  mongo:
    image: mongo:latest
    container_name: jatb_mongo
    env_file: .env
    restart: always
    environment:
      - MONGO_INITDB_DATABASE=${MONGO_INITDB_DATABASE}
      - MONGO_INITDB_ROOT_USERNAME=${MONGO_INITDB_ROOT_USERNAME}
      - MONGO_INITDB_ROOT_PASSWORD=${MONGO_INITDB_ROOT_PASSWORD}
      # - MONGODB_ENABLE_ADMIN=false
    volumes:
      - './mongo-volume:/data/db'

volumes:
  mongodb_data:
    driver: local
